/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quebracabeca;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author labcom
 */
public class quebracabecaJFRAME extends javax.swing.JFrame { // é uma herança, pois quebracabecaJFRAME é uma continuidade do JFrame
    
    ArrayList<Integer> lista = new ArrayList<>();
    Integer[] listacerta = new Integer[16];
    int nj=0;
    
    JButton botao2 = new JButton(); //os botões (JButton) são objetos privados, instâncias do javax.swing
    
    
    
    
    /**
     * Creates new form quebracabecaJFRAME
     */
    public quebracabecaJFRAME() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 60));
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, 60));
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, 60));
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 80, 60));
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 60));
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 60));
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 60));
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, 60));
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 60));
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 60));
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 60));
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 60));
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 60));
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 80, 60));
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 60));
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("texto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        embaralhar();
    }//GEN-LAST:event_formWindowOpened
    
    
    public void embaralhar(){
        //limpando a lista
        lista.clear();
        
        //adicionando 15 numeros ao array list
        for (int i = 1; i <= 15; i++){
            lista.add(i);
        }
        
        lista.add(null);
        
        Collections.shuffle(lista);
        
        b1.setText (lista.get(0) != null ? lista.get(0).toString() : "");
        b2.setText (lista.get(1) != null ? lista.get(1).toString() : "");
        b3.setText (lista.get(2) != null ? lista.get(2).toString() : "");
        b4.setText (lista.get(3) != null ? lista.get(3).toString() : "");
        b5.setText (lista.get(4) != null ? lista.get(4).toString() : "");
        b6.setText (lista.get(5) != null ? lista.get(5).toString() : "");
        b7.setText (lista.get(6) != null ? lista.get(6).toString() : "");
        b8.setText (lista.get(7) != null ? lista.get(7).toString() : "");
        b9.setText (lista.get(8) != null ? lista.get(8).toString() : "");
        b10.setText(lista.get(9) != null ? lista.get(9).toString() : "");
        b11.setText(lista.get(10) != null ? lista.get(10).toString() : "");
        b12.setText(lista.get(11) != null ? lista.get(11).toString() : "");
        b13.setText(lista.get(12) != null ? lista.get(12).toString() : "");
        b14.setText(lista.get(13) != null ? lista.get(13).toString() : "");
        b15.setText(lista.get(14) != null ? lista.get(14).toString() : "");
        b16.setText(lista.get(15) != null ? lista.get(15).toString() : "");
        

        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quebracabecaJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quebracabecaJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quebracabecaJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quebracabecaJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quebracabecaJFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
